### ISSUE TITLE
Compile errors on VSMac

### ISSUE THREAD

**Issue by davidortinau** [OYIon/LiveXAML#18]
Mono 5.4.0.135
VSMac 7.2 Alpha channel

Tried a couple projects, PCL and Shared, and a new blank project. Perhaps I'm missing a setup step.

Steps:
- File > New > Blank shared project, iOS only
- Add LiveXAML 1.2.29 to iOS head
- Run to iOS Simulator

2 Errors:
/Users/dave/Projects/WantLiveXaml/packages/LiveXAML.1.2.29/build/minified.cs(58,58): Error CS0103: The name 'XDocument' does not exist in the current context (CS0103) (WantLiveXaml.iOS)

/Users/dave/Projects/WantLiveXaml/packages/LiveXAML.1.2.29/build/minified.cs(68,68): Error CS1579: foreach statement cannot operate on variables of type '?' because '?' does not contain a public definition for 'GetEnumerator' (CS1579) (WantLiveXaml.iOS)

**Comment by ionoy** [comment]
Hello David,

Can you make sure that `System.Xml.Linq.dll` assembly is referenced?

Thanks for the feedback!

**Comment by ionoy** [comment]
I did some more research and it seems like LiveXAML will have to use `XmlReader` instead of `XDocument`, because `System.Xml.Linq` is not referenced by default. I thought about using `XmlDocument`, but it's not supported by PCL projects.

Thanks for bringing this to my attention. I can give you a discount if you ever interested in purchasing a license.

**Comment by ionoy** [comment]
I have uploaded the new version of NuGet package. It should resolve the issue with iOS compilation. Please try it and see if it works.

Thanks!
